export default function (fn) {
  // Provides a wrapper to catch rejected promises in async routes
  return (req, res, next) => {
    const routePromise = fn(req, res, next);
    if (routePromise.catch) {
      routePromise.catch(err => next(err));
    }
  };
}
